color:
  brandStrength: 1
  saturation: 0.2744681
  brandColors:
    - '#F4F3F0'
    - '#EAB698'
    - '#1F211F'
    - '#A499A2'
    - '#776D6F'
  lightness: 0.5106383
  rhythmicContrast: 0.4680851
analytics:
  facebook: null
  google: null
  twitter: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  version: null
  bucket: null
favicon: null
layout_spectrum: 0.2829787
purpose: []
name: IS
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5212766
