name: SometimeinAugust
favicon: null
layout_spectrum: 0.2829787
typography_spectrum: 0.5212766
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F4F3F0'
    - '#EAB698'
    - '#1F211F'
    - '#A499A2'
    - '#776D6F'
  brandStrength: 1
  lightness: 0.5106383
  saturation: 0.2744681
  rhythmicContrast: 0.4680851
purpose: []
